services:
  mcp-server:
    extends:
      file: ./mcpserver/compose.yml
      service: mcp-server
  mcp-client:
    extends:
      file: ./mcpclient/compose.yml
      service: mcp-client
    depends_on:
      mcp-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=openai,local
      - SPRING_AI_OLLAMA_BASE_URL=http://host.docker.internal:11434
      - SPRING_AI_MCP_CLIENT_SSE_CONNECTIONS_SERVER1_URL=http://host.docker.internal:4280
      - SPRING_AI_MCP_CLIENT_SSE_CONNECTIONS_SERVER1_SSE-ENDPOINT=/sse